name: 'publish'

on:
    push:
        tags:
            - 'v*'

# Triggers on git tags starting with 'v' (e.g., v1.0.0)
# Creates a GitHub release, builds your app, and uploads the artifacts to the release.

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: 'macos-latest' # for Arm based macs (M1 and above).
                      args: '--target aarch64-apple-darwin'
                    - platform: 'macos-latest' # for Intel based macs.
                      args: '--target x86_64-apple-darwin'
                    - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
                      args: ''
                    - platform: 'windows-latest'
                      args: ''
                    - platform: 'ubuntu-22.04' # Android build
                      args: '--target aarch64-linux-android'
                      mobile: true
                    - platform: 'ubuntu-22.04' # Android build
                      args: '--target armv7-linux-androideabi'
                      mobile: true
                    - platform: 'macos-latest' # iOS build
                      args: '--target aarch64-apple-ios'
                      mobile: true
                    - platform: 'macos-latest' # iOS simulator
                      args: '--target aarch64-apple-ios-sim'
                      mobile: true

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.mobile && (contains(matrix.args, 'android') && 'aarch64-linux-android,armv7-linux-androideabi' || contains(matrix.args, 'ios') && 'aarch64-apple-ios,aarch64-apple-ios-sim' || '') || matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

            - name: Setup Java (Android only)
              if: matrix.mobile && contains(matrix.args, 'android')
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Setup Android SDK (Android only)
              if: matrix.mobile && contains(matrix.args, 'android')
              uses: android-actions/setup-android@v3

            - name: Install Android NDK (Android only)
              if: matrix.mobile && contains(matrix.args, 'android')
              run: |
                  sdkmanager "ndk;25.2.9519653"
                  echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
              # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
              # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

            - name: install frontend dependencies
              run: pnpm install

            - name: Get package version
              id: package-version
              run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
              shell: bash

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
                  VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
                  VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
                  VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
                  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
                  VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
                  VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
                  NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
              with:
                  tagName: v${{ steps.package-version.outputs.version }}
                  releaseName: 'App v${{ steps.package-version.outputs.version }}'
                  releaseBody: 'See the assets to download this version and install.'
                  releaseDraft: true
                  prerelease: false
                  args: ${{ matrix.args }}
